name: golangci-lint
on:
  push:
    branches:
      - master
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  golangci:
    name: Go Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false
      - name: golangci-lint (code)
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.56.2
          skip-cache: true
          install-mode: "binary"
      - name: golangci-lint (benchmarks)
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.56.2
          skip-cache: true
          install-mode: "binary"
          working-directory: benchmarks
